### ISSUE TITLE
fatal error: ./algorithms.h

### ISSUE THREAD

**Issue by tmelorc** [luetge/flagser#2]
When running `make` I get the following error (my translataion): 

`/home/thiago/Downloads/flagser/src/../include/complex/../filtration_algorithms.h:54:26: fatal error: ./algorithms.h: file or dir folder not found` 

I checked the `src` folder and there is no such file `./algorithms.h`. Any help?
Thanks in advance.

(full output below):

> [  5%] Check for custom algorithms
> [  5%] Built target generate_custom_algorithms
> [ 10%] Building CXX object CMakeFiles/flagser-coefficients.dir/src/flagser.cpp.o
> In file included from /flagser/src/../include/complex/directed_flag_complex_computer.h:10:0,
>                  from /flagser/src/flagser.cpp:25:
> /flagser/src/../include/complex/../filtration_algorithms.h:54:26: fatal error: ./algorithms.h: Arquivo ou diretório não encontrado
> compilation terminated.
> CMakeFiles/flagser-coefficients.dir/build.make:62: recipe for target 'CMakeFiles/flagser-coefficients.dir/src/flagser.cpp.o' failed
> make[2]: *** [CMakeFiles/flagser-coefficients.dir/src/flagser.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/flagser-coefficients.dir/all' failed
> make[1]: *** [CMakeFiles/flagser-coefficients.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by tmelorc** [comment]
The problem was solved running `math_parser.py` from `parser` folder before running `make`.

**Comment by luetge** [comment]
Thanks for the report, there was indeed a missing file. I added it in commit 52b81661d14e8d3ef5ab86806dae4dba5e3782f7, it should now work without running the math parser.

**Comment by tmelorc** [comment]
Nice! Thanks for attention. It would be good also to have some example files in some folder. The user guide tells how to run an example but there is no such file. Regards.
