### ISSUE TITLE
"there is an error in the program" - euler characteristic

### ISSUE THREAD

**Issue by jlazovskis** [luetge/flagser#22]
Hi Daniel - came across this message when running flagser (downloaded flagser last night from here). Flagser runs and outputs the flag file correctly (I assume). 

```
./../flagser/flagser --out out step0
The dimensions of the mod-2 homology of the full complex are:

dim H_0 = 31346
dim H_1 = 6953
The Euler characteristic is given by: 24394
ERROR: The homological Euler characteristic (which is 24393) differs from the cellular Euler characteristic (which is 24394), apparently there is an error in the program.
```

Here is the input file: https://pastebin.com/hrWUW36d

For context, this is part of a project @JasonPSmith and I are working on at Aberdeen. The input is the transmission response flag of a test stimulus on BlueBrain's mc2 column made in the NEST simulator. 

**Edit:** The file i linked to was quite degenerate - every edge was a loop. Here's another file with no loops, no double edges, and no 2-cycles. This file still gives the same message (with slightly lower counts 22379 / 22380): https://pastebin.com/tR2kPXuW 

**Edit 2:** Looks like the problem was that there not enough zeros in dim0 to account for all the indices in dim1 (thanks for catching that @JasonPSmith). Removing the too-high index and rerunning flagser no longer produces the message. Here is a minimal example that gives the same "error in the program" message:

```
dim 0
0
dim 1
1 2
```

**Comment by luetge** [comment]
Hi,

sorry for the very late reply, life was quite busy here and this seemed to be a more delicate problem. Happy you figured it out, I will add a message that gives an error when this happens. Will close the ticket as soon as that is implemented.

Thanks for figuring out the problem!

Cheers,
Daniel

**Comment by luetge** [comment]
See #24
