### ISSUE TITLE
Arguments management in Flagser

### ISSUE THREAD

**Issue by MonkeyBreaker** [luetge/flagser#29]
Hi !

I have a question about how `flagser` manages command line arguments.
Currently, the arguments are "managed" with:

```c++
auto positional_arguments = get_positional_arguments(arguments);
auto named_arguments = get_named_arguments(arguments);

/* Later in the code */
if ((it = named_arguments.find("<arg>")) != named_arguments.end()) { <var> = <operation>(it) }
```

And this `Later in the code` is found in different files, not only on the configuration part.

What I would like to suggest is to have a structure containing all the potential arguments, create a function where we centralized the processing of the arguments and load then into the structure (or it can return an object). And then we only continue with this object instead of moving with `named_arguments` when required.

I can create a PR with all the code updated to reflect the changes described, but I want first a feedback to know if you would have any suggestion about this ?

Also for us, doing this would make more clear our bindings for Python in `pyflagser`.

Best,
Julián

**Comment by luetge** [comment]
Sounds great, happy to review a pull request for that!

**Comment by luetge** [comment]
Thanks a lot for the contribution !
