### ISSUE TITLE
flagser

### ISSUE THREAD

**Issue by mp2m15** [luetge/flagser#3]
Dear Dr. Lutgehetmann

I have come across your software flagser. However, I was unable to build it. I am using a Mac. The error I got was
Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 

If you have any suggestions, I would be very grateful.

With kind regards,
M.P.

**Comment by luetge** [comment]
Hi, there was indeed a problem in the configuration that prevented proper building without HDF5 support. In the newest version on the master branch it should compile, I just pushed the fix. Let me know if this still gives you problems, otherwise we can close this issue.

**Comment by mp2m15** [comment]
Thank you! Yes, I managed to build flagser now. I do have another question, though. The option out-format can be set to betti or barcodes. However, I was unable to set it to barcodes.

Your help would be greatly appreciated.

Best wishes,
M.P.
________________________________

**Comment by luetge** [comment]
Any output of the failing command? For me, the following works for example:
```
./flagser --out-format barcode --out example.homology test/medium-test-data.flag 
```

Could you try it and post the log? Thanks!

**Comment by mp2m15** [comment]
I see, the option name is barcode, not barcodes! Yes, this did work, thank you.
________________________________

**Comment by luetge** [comment]
You're welcome!
