### ISSUE TITLE
(cleanup) remove references for in-memory-flag-complex in flagser-count.cpp as it is not used(?)

### ISSUE THREAD

**Issue by flomlo** [luetge/flagser#33]
Hi,

either I debugged incorrectly the last few hours or flagser-count does *not* make use of the KEEP_FLAG_COMPLEX_IN_MEMORY flag and thus the directed_flag_complex_in_memory[_computer].h files.

To be more precise: Even if compiled with that compile-flag, only `directed_flag_complex_t` is used in flagser-count.cpp,  which is only defined in directed_flag_complex.h. 

Furthermore I both analyzed the compiled binary with `gdb` and with `objdump` and could not find any references to the in-memory versions.

Did I do something wrong (definitely possible, it's the first time I looked at C++ code!) or is the code burdened by a bit of unused code?

The flagser.cpp does make use of the in-memory-versions however.

**Comment by luetge** [comment]
Indeed correct, I fixed it. Thanks for checking!
