### ISSUE TITLE
In memory performances

### ISSUE THREAD

**Issue by MonkeyBreaker** [luetge/flagser#35]
Hi !

Some user are requesting to integrate the `in memory` version of flagser inside our python flagser bindings  library ([pyflagser](https://github.com/giotto-ai/pyflagser)).

After doing some measurements with the test examples for both `flagser` and `flagser_in_memory`, I got the following results:

About small and big in the following tables, it's related to the function called inside of `test_flagser.cpp` and `test_flagser_memory.cpp` files.

* small => run_all(false);
* big => run_all(true);

## runtime [s]

| normal (small) | normal (big) | in memory (small) | in memory (big) |
|----------------|--------------|-------------------|-----------------|
| 0.05           | 75           | 0.05              | 72              |

## Memory [GB]

| normal (small) | normal (big) | in memory (small) | in memory (big) |
|----------------|--------------|-------------------|-----------------|
| 0.007          | 0.57         | 0.007             | 0.53            |

Memory consumption is similar, but the in memory performance is around 4% faster.

I wanted to know from your experience if this is kind of expected performances or the more we increase the dataset size, the more we should  get a gain when using `in memory` version ?

Best,
Julián

**Comment by MonkeyBreaker** [comment]
Okay I found out about this small difference in performances.

I was using the test programs to measure performances, `test_flagser` and `test_flagser_memory`.
But after looking into `base.h`, I found out that for `test_flagser_memory` the data structure `directed_flag_complex_in_memory_computer` was not used, that it used the same data structure as `test_flagser`.

After fixing the matter, the new benchmark gives more expected results:

## runtime [s]

| normal (small) | normal (big) | in memory (small) | in memory (big) |
|----------------|--------------|-------------------|-----------------|
| 0.05           | 75           | 0.05              | 65              |

## Memory [GB]

| normal (small) | normal (big) | in memory (small) | in memory (big) |
|----------------|--------------|-------------------|-----------------|
| 0.007          | 0.57         | 0.007             | 1.4            |

With the in memory version being around 10% faster but consumes at peak of this benchmark 3 times more memory.

In my opinion, this results seems more expected, what do you think ?

Best,
Julián

**Comment by luetge** [comment]
Hi Julián,

Thanks for taking the time to do the benchmark! This seems to be indeed more likely to be the correct trade-off. The main difference between memory and non-memory is that you can have an efficient lookup in the data structure instead of relying on hashing for looking up indices of simplices. Depending on the use case, this can have huge performance differences, either in terms of compute time or memory, so choosing the appropriate version is important.

Thanks for your contribution!

Best, Daniel
