### ISSUE TITLE
comment wrongly copypasted in definition.h (regarding MANY_VERTICES)

### ISSUE THREAD

**Issue by flomlo** [luetge/flagser#37]
Hi,

this line:
https://github.com/luetge/flagser/blob/292bcf15202eaa27a81612acfb746235bed56480/include/definitions.h#L15

is just a copypaste of line 11 (same file).

My understanding is however, that line 15 should be more like "// In case of more then 65k vertices, we might also have more then ~2 billion cells".

Nothing major, but it caught my eye :)

**Comment by luetge** [comment]
Thanks!
