### ISSUE TITLE
flagser-count and flagser produce wrong results in case of `vertex_type_t` overflow

### ISSUE THREAD

**Issue by flomlo** [luetge/flagser#39]
Hi,

`flagser-count` (and `flagser`)  produce incorrect results on due to unchecked overflows. This is particularly noticeable if compiled without `MANY_VERTICES`.

The flag file x.flag contains a graph with 2^16 +1 vertices and only one edge from 2^16 to 0.
The result is 
```
[florian@frankenstein-archlinux build]$ ./flagser-count /tmp/x.flag.txt --out /tmp/fu.bla
# [euler_characteristic cell_count_dim_0 cell_count_dim_1 ...]
0 1 1
```
Which is clearly wrong, as the graph has more 0-simplices.

A proposed fix would check for overflows in line https://github.com/luetge/flagser/blob/292bcf15202eaa27a81612acfb746235bed56480/include/directed_graph.h#L123 and warn the user.

I will file a PR soon.

[x.flag.txt](https://github.com/luetge/flagser/files/6216272/x.flag.txt)

**Comment by luetge** [comment]
Thanks!
