### ISSUE TITLE
Are cycles made from bidirectional edge supposed to be generators of homology?

### ISSUE THREAD

**Issue by vonpost** [luetge/flagser#42]
In traditional simplicial homology an equivalence is usually made to say that the opposite orientation of a simplex is supposed to be its additive inverse in the chain group. However, in Flagser we have that the directed graph given by an bidirectional edge going between two vertices
```
dim 0
0 0
dim 1
0 1 1
1 0 1
```
yields the output 
```
Betti numbers (between 0 and 1):
1 1 
```
in other words, there is a non-trivial 1-cycle given by the cycle  (0 -> 1) + (1 -> 0). Normally, (0 -> 1) + (1 -> 0) = (0 -> 1) - (0 -> 1) = 0 in homology due to the identification of the permutation as an inverse. But clearly this is not the case in Flagser.

Is this absence of equivalences in the chain module intentional? I cannot find any mention of it or its implications.

**Comment by luetge** [comment]
Hi,

In this case there are two distinct edges (we are working with a *directed* flag complex), and there is no explicit identification of those two edges (meaning (0 -> 1) != - (1 -> 0)). Therefore, the non-trivial first homology is working as intended.

Best,
Daniel
