### ISSUE TITLE
Flagser not works for persistence

### ISSUE THREAD

**Issue by oleg-kachan** [luetge/flagser#5]
Dear Daniel,

Flagser does not work for me in terms of persistent homology, even on the data provided as an example.

Attaching the output file obtained by running the following command:

./flagser --out-format barcode --out example.homology test/medium-test-data.flag

As you can see persistence intervals all starting with 0 with no closing element.

Also, if I do not use the key "--out-format barcode" which in documentation is marked as default, no any persistence intervals are present in the output file, so I forced to use it. It seems that library is only able to compute the number of simplices, Betti numbers, and Euler characteristic.

Would you be so kind as to help me to overcome this problem?

Thank you in advance.

PS: I have compiled Flagser both on Mac (clang-1000.11.45.5, Ubuntu 16.04 (gcc Ubuntu 5.4.0-6ubuntu1 16.04.10 5.4.0 20160609), Ubuntu 18.04 (gcc Ubuntu 7.3.0 27ubuntu1~18.04 7.3.0)

Attachment: https://wetransfer.com/downloads/83a391cde817457a588edb3a3ec077c820190205135454/ff4bc49ec369c0a95243caddf9dcd8af20190205135454/5895f7

**Comment by luetge** [comment]
Hi,

sorry for the confusing CLI options: by default, the trivial filtration algorithm is used. You can set the strategy to compute simplex filtrations from vertex/edge filtrations to eg --filtration max, giving the simplex the maximal filtration values of all of it's faces. Your call then becomes

./flagser --out-format barcode --filtration max --out example.homology test/medium-test-data.flag

I will add this to the documentation and possibly switch to the max filtration algorithm in case a non-trivial filtration is given. Thank you for the comment!

**Comment by oleg-kachan** [comment]
Dear Daniel,

Could you please describe filtration algorithms? I have a graph with weighted edges, with weights given by the positive part of the Pearson correlation. So I want edges with highest weights added to the filtration first and edges with lowest weights added to the filtration last.

Which Flagser filtration corresponds to that desired behavior? Does it perform filtration in ascending or descending order according to weight function?

Also, how vertices weights affect the computation? Does "max" filtration sets a filtration value to the simplex containing a set of vertices to the maximum value of filtration function on vertices? But in my case, all vertices weights are not defined (I set them to zero) and I have weights on edges.

Thanks.
